host: localhost
port: 2000
num_npcs: 15
img_width: 640
img_height: 480
conf_thres: 0.3
iou_thres: 0.3
max_age: 8
min_hits: 3
yolo_imgsz_max: 320  
yolo_iou: 0.45
kf_dt: 0.05
max_speed: 50.0
window_width: 1280 
window_height: 720   
smooth_alpha: 0.2
fps_window_size: 15
display_fps: 30  

track_history_len: 20
track_line_width: 2
track_alpha: 0.6


stop_speed_thresh: 1.0
stop_frames_thresh: 5
overtake_speed_ratio: 1.5
overtake_dist_thresh: 50